#!/bin/bash
set -e

# shellcheck disable=SC2155
export bold=$(tput bold)
# shellcheck disable=SC2155
export normal=$(tput sgr0)
# shellcheck disable=SC2155
export red=$(tput setaf 1)

case "${1}" in
	generate)
		if ! source ./manifest; then
			echo -e "${red}Failed to read manifest${normal}"
			exit 1
		fi
		if test -f bpm.lock; then
			echo "Removing stale bpm.lock"
			rm -f bpm.lock
		fi
		for i in "${dependencies[@]}"; do
			echo "Adding: $i"
			echo "$(cut -d@ -f1 <<< $i)@$(git ls-remote https://github.com/$(cut -d@ -f1 <<<$i).git | awk '{print $1;}' | head -n 1)" >> bpm.lock
		done
		exit
	;;
	update)
		if ! source ./manifest; then
			echo -e "${red}Failed to read manifest${normal}"
			exit 1
		fi
		if [[ ${#dependencies[@]} -eq 0 ]]; then
			echo "${red}Empty dependencies list${normal}"
			exit 1
		fi
		for i in "${dependencies[@]}"; do
			local_version="$(cut -d@ -f2 <<< $i)"
			latest_tag="$(git ls-remote --tags https://github.com/$(cut -d@ -f1 <<< $i) | awk '{ print $2 }' | cut -d"/" -f3 | sort | tail -n 1)"
			# check if major update is possible
			if ! semver diff "$local_version" "$latest_tag" | grep -q 'major'; then
				upgrading+=("$(cut -d@ -f1 <<< $i)@$latest_tag")
				echo "==> $(cut -d@ -f1 <<< $i)@$local_version -> $(cut -d@ -f1 <<< $i)@$latest_tag"
			else
				upgrading+=("$(cut -d@ -f1 <<< $i)@$local_version")
				check+=("$(cut -d@ -f1 <<< $i)@$local_version")
				echo -e "${red}==> $(cut -d@ -f1 <<< $i)@$local_version != $(cut -d@ -f1 <<< $i)@$latest_tag${normal}"
			fi
		done
		echo -e "\n${red}These packages will need to be manually checked for breaking behavior before upgrading${normal}"
		echo -e "\t${check[*]}\n"
		echo -e "\nReplace your manifest with this and then run '${bold}bpm generate${normal}', followed '${bold}bpm pull${normal}"
		echo -e "\ndependencies=("
		for i in "${upgrading[@]}"; do
			echo -e "\t$i"
		done
		echo ")"
		exit
	;;
	pull)
		if ! source ./manifest; then
			echo -e "${red}Failed to read manifest${normal}"
		fi
		for line in $(cat bpm.lock); do
			mkdir -p $HOME/.local/state/bpm/$bpm_name/"$(cut -d@ -f1 <<< $line | cut -d'/' -f1)"
			cd $HOME/.local/state/bpm/$bpm_name/"$(cut -d@ -f1 <<< $line | cut -d'/' -f1)"
			if [[ -d "$(cut -d@ -f1 <<< $line | cut -d'/' -f2)" ]]; then
				echo "Overwriting old directory"
				rm -rf "$(cut -d@ -f1 <<< $line | cut -d'/' -f2)"
			fi
			git clone --filter=blob:none -j 20 -q https://github.com/"$(cut -d@ -f1 <<< $line)" $(cut -d@ -f1 <<< $line | cut -d'/' -f2)
			cd "$(cut -d@ -f1 <<< $line | cut -d'/' -f2)"
			git checkout -q "$(cut -d@ -f2 <<< $line)"
			if test -f "bpm.sh"; then
				echo "Running post-clone script"
				./bpm.sh
			fi
		done
	;;
	*)
		exit 1
	;;
esac
